### ISSUE TITLE
OpenShift DeploymentConfigs depreciation warning

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-fam-idim-lookup-proxy#105]
**Describe the task**
Same as FOM, we also need to do the upgrade with this project.
![image](https://github.com/user-attachments/assets/d6eb15b4-c7e2-4221-ae77-0be797f1556c)

**Acceptance Criteria**
- [ ] first

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by gormless87** [comment]
@DerekRoberts - please review and advise regarding potential outage required.

**Comment by DerekRoberts** [comment]
@gormless87 Done!  Please see PR https://github.com/bcgov/nr-fam-idim-lookup-proxy/pull/107 for outage info.  I can work with your team or handle the deployment during an outage window.
