### ISSUE TITLE
IDIM-webservice-proxy

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-fam-idim-lookup-proxy#16]
**Describe the task**
Deploy a minimally changed clone of the Pathfinder SSO code 

**Acceptance Criteria**
- [ ] Acceptable security in place
- [ ] Connectivity test from developer postman (O/S VPN) 

**Additional context**
- https://github.com/bcgov/sso-realm-registry/tree/dev/app/pages/api/bceid-service
- minimal security : hardcoded token (API key as GH+OpenShift secret), rely on TLS

**Comment by ianliuwk1019** [comment]
Some IDIM lookup information from previous [ticket](https://app.zenhub.com/workspaces/fsa-fingerprint-61f04f08304d3e001a4f2578/issues/gh/bcgov/nr-forests-access-management/483).

**Comment by MCatherine1994** [comment]
- [ ] add SOAP API call to search idir user
- [ ] add environment variable in pipeline
- [ ] test in openshift 
- [ ] add security token
- [ ] add tests
