### ISSUE TITLE
Return first name, last name and email in the search result

### ISSUE THREAD

**Issue by MCatherine1994** [bcgov/nr-fam-idim-lookup-proxy#86]
**Describe the task**
Return first name, last name and email in the search result for searching both IDIR and BCeID user

**Acceptance Criteria**
- [x] Add the first name, last name and email to the return result for both IDIR and BCeID user

**Additional context**
- For BCeID:
![Image](https://github.com/bcgov/nr-fam-idim-lookup-proxy/assets/23131735/c7159295-da16-4bb4-aa55-23cf6a221845)
![Image](https://github.com/bcgov/nr-fam-idim-lookup-proxy/assets/23131735/c7c1b87a-36b6-4569-a250-4833f57c047b)
- For IDIR:
![Image](https://github.com/bcgov/nr-fam-idim-lookup-proxy/assets/23131735/b8a042ee-2e2b-44c3-a83b-1da2b2a63410)
![Image](https://github.com/bcgov/nr-fam-idim-lookup-proxy/assets/23131735/4e1c2caf-e5e5-4ac8-ad04-66377dac29a8)

**Comment by MCatherine1994** [comment]
This is related to FAM ticket https://github.com/orgs/bcgov/projects/65/views/1?filterQuery=first&pane=issue&itemId=62315607

**Comment by MCatherine1994** [comment]
this one seems already done

**Comment by ianliuwk1019** [comment]
Verified, this is done at idim-lookup-proxy repo.
